### ISSUE TITLE
How to correctly add Source Modifiers for genbank submisson?

### ISSUE THREAD

**Issue by ammaraziz** [CDCgov/seqsender#8]
Hi,

Thanks for creating and maintaining this very useful program. 

I am trying to include patient metadata for the NCBI submission part of the process. Similar to gisaid which allows `gender`, `passage` etc, NCBI allows source modifiers such as `sex`.

I am not 100% sure how to include such information for the NCBI part of the metadata in the config file.

```
genbank_src_metadata:
  column_names:
    isolate: genbank_name
    host: host
    country: location
    isolation-source: isolation_source
```

Lets say I wanted to include the ncbi source modifier `Sex` (assuming I have a column in my metadata called `gender`), would I add the following:
```
genbank_src_metadata:
  column_names:
  ....
  Sex: gender
```

Is that correct?

A related question, for the structured data section eg:

```
COMMENT     ##Assembly-Data-START##
                        Assembly Method       :: CLC Genomics
                        Sequencing Technology :: PacBio Sequel II
                        ##Assembly-Data-END##
```

How can I add more information than? 

My main aim is to match all the metadata that is required in gisaid to ncbi submission.

Thanks,

Ammar
